### ISSUE TITLE
Save File won't load.

### ISSUE THREAD

**Issue by MrBurb** [FINDarkside/TLD-Save-Editor#46]
Whwn I open the save editor i get an error that says the save file failed to load. It says:

"`Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at The_Long_Dark_Save_Editor_2.Tabs.MapTab.<.ctor>b__6_0(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at The_Long_Dark_Save_Editor_2.MainWindow.SetPropertyField[T](T& field, T newValue, String propertyName)
   at The_Long_Dark_Save_Editor_2.MainWindow.CurrentSaveSelectionChanged(Object sender, SelectionChangedEventArgs e)`" 

It is like this for all of my saves and I don't know how to fix it.

**Comment by FINDarkside** [comment]
Apparently reinstalling TLD fixed the issue.
